###
# 1: Obtener el listado completo de usuarios
###

GET http://localhost:1234/usuarios
###
GET http://localhost:1234/productos

###
# 2: Obtener datos de un usuario por ID
###

GET http://localhost:1234/usuarios/7

###
# 3: Crear un nuevo usuario
###

POST http://localhost:1234/usuarios/new
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXIiOiJtcmllcmFAZXhhbXBsZS5jb20iLCJleHAiOjE2OTczMzAxMDczMzEsImlhdCI6MTY5NzMyOTgwN30.OIrq-Ohi3Cufk5U0kY4hNjKckeNQ4Grq5-UoNCSrqMY

{
  "id": 9,  
  "dni": 33333333,
  "nombre": "Jorge",
  "apellido": "Sica",  
  "email": "jorgesica@ejemplo.com",
  "telefono": "+342 123 1236", 
  "password": "1234567"
}

###
# 4: Modificar atributos de un usuario por ID
###

PATCH http://localhost:1234/usuarios/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjUsInVzZXIiOiJtcmllcmFAZXhhbXBsZS5jb20iLCJleHAiOjE2OTczMzAxMDczMzEsImlhdCI6MTY5NzMyOTgwN30.OIrq-Ohi3Cufk5U0kY4hNjKckeNQ4Grq5-UoNCSrqMY

{ 
  "nombre": "Luke Skywalker"
}

###
# 5: Borrar un usuario por ID
###

DELETE http://localhost:1234/usuarios/2

###
# 6: Obtener el precio de un producto por ID
###

GET http://localhost:1234/productos/1/precio

###
# 7: Obtener el nombre de un producto por ID
###

GET http://localhost:1234/productos/1/nombre

###
# 8: Obtener el teléfono de un usuario por ID
###

GET http://localhost:1234/usuarios/1/telefono

###
# 9: Obtener el nombre de un usuario por ID
###

GET http://localhost:1234/usuarios/1/nombre

###
# 10: Obtener el total del stock actual de productos
###

GET http://localhost:1234/productos/total

###
# 11: Respuesta desde el formulario de log en el front
###
POST http://localhost:1234/auth
Content-Type: application/json

{
  "email": "mriera@example.com",
  "password": "passMatias"
}