###
# 1: LOG COMO ADMIN
###
POST http://localhost:8000/auth
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "passAdmin"
}
###
# 1.1 : LOG COMO USER
###
POST http://localhost:8000/auth
Content-Type: application/json

{
  "email": "jlopez@example.com",
  "password": "passJorge"
}
###
# 1.2: LOG COMO PROVEEDOR
###
POST http://localhost:8000/auth
Content-Type: application/json

{
  "email": "infomex@example.com",
  "password": "passInfomex"
}


###
# 2: Obtener el listado completo de usuarios y productos
###
GET http://localhost:8000/usuarios/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2ODI2MzQ3LCJpYXQiOjE2OTg5NjY1MjZ9.ZuV00izBtrfX6eVt7iVcgDweie0rkhQPOwkAAeSxOv0
###
# 2.1: Obtener el listado completo de productos
###
GET http://localhost:8000/productos

###
# 3: Obtener datos de un usuario y producto por ID 
###
GET http://localhost:8000/usuarios/14
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2NDYyNTYzLCJpYXQiOjE2OTg5NjYxNjJ9.kXdzk1olE8lteSaqZ3ttixb3q8MQvYkkg57QZljFU38

###
# 3.1: Obtener datos de un producto por ID 
###
GET http://localhost:8000/productos/2

###
# 4: Cambiar usuario comun a proveedor
###
PATCH http://localhost:8000/usuarios/nuevoProveedor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2ODQ3NDM0LCJpYXQiOjE2OTg5NjY1NDd9.-Mo29DoZtK17YyLJcSAH323aKBjP-c_ofbX_CwXoKy0

{  
  "id": 20
}

###
# 5: Crear un nuevo usuario
###
POST http://localhost:8000/usuarios/
Content-Type: application/json

{  
  "dni": 12345678,
  "nombre": "Carlos",
  "apellido": "Gonzalez",  
  "email": "cgonzalez@ejemplo.com",
  "telefono": "+342 123123123",
  "password": "passCarlos"
}

###
# 6: Crear un nuevo producto
POST http://localhost:8000/productos/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2OTk1OTQ2LCJpYXQiOjE2OTg5NjY2OTV9.Qq7j8IX3AnCCQE4ULXU1f8PNIlW7696VPRT5QTpk2og

{  
  "nombre": "Disco duro",
  "tipo": "Informatica",
  "precio": 6500,
  "stock": 100 
}

###
# 7: Modificar atributos de un usuario por ID
###
PATCH http://localhost:8000/usuarios/14
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2OTk1OTQ2LCJpYXQiOjE2OTg5NjY2OTV9.Qq7j8IX3AnCCQE4ULXU1f8PNIlW7696VPRT5QTpk2og

{ 
  "nombre": "Matias Gabriel"
}

###
# 7.1: Modificar atributos de un producto por ID
###
PATCH http://localhost:8000/productos/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2OTk1OTQ2LCJpYXQiOjE2OTg5NjY2OTV9.Qq7j8IX3AnCCQE4ULXU1f8PNIlW7696VPRT5QTpk2og

{ 
    "codigo": "COD-003",
    "nombre": "Teclado",
    "tipo": "Informatica",
    "precio": 1520,
    "stock": 13
}


###
# 8: Actualizar stock de productos
###
PATCH http://localhost:8000/productos/actualizar-stock
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2OTk1OTQ2LCJpYXQiOjE2OTg5NjY2OTV9.Qq7j8IX3AnCCQE4ULXU1f8PNIlW7696VPRT5QTpk2og

{ 
    "sku": "COD-001",    
    "stock": 30000
}

###
# 9: Borrar un usuario por ID
###
DELETE http://localhost:8000/usuarios/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2OTk1OTQ2LCJpYXQiOjE2OTg5NjY2OTV9.Qq7j8IX3AnCCQE4ULXU1f8PNIlW7696VPRT5QTpk2og

# 9.1: Borrar un producto por ID
###
DELETE http://localhost:8000/productos/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2OTk1OTQ2LCJpYXQiOjE2OTg5NjY2OTV9.Qq7j8IX3AnCCQE4ULXU1f8PNIlW7696VPRT5QTpk2og

###
# 10 : Crear carrito de compras
POST http://localhost:8000/carrito/nuevo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2OTk1OTQ2LCJpYXQiOjE2OTg5NjY2OTV9.Qq7j8IX3AnCCQE4ULXU1f8PNIlW7696VPRT5QTpk2og

{
  "sku" : "COD-001",
  "cantidad": 2
}

###
# 10.1 : Ver carrito de compras
GET http://localhost:8000/carrito/vista/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjE1LCJ1c2VyIjoiaW5mb21leEBleGFtcGxlLmNvbSIsInJvbCI6MywiZXhwIjoxNjk4OTY2NDg4OTI0LCJpYXQiOjE2OTg5NjYxODh9.CUm_U1p32iZ-vp6XX8E7vZMwtJ5_G4mgjPv05wxy-0s

